language: ruby

rvm:
  - 1.9.3

env:
  - DB=postgresql

branches:
  only:
    - 'master'

script:
  - bundle exec rake db:create:all --trace
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - bundle exec rspec spec/

before_script:
  - psql -c 'create database railsforcharity_test' -U postgres
  - cp config/database.travis.yml config/database.yml

bundler_args: "--without development"
