markdown: rdiscount
permalink: /:title.html
destination: ../../public/blog
auto: true
exclude:
  - Rakefile
  - Gemfile
  - .gitignore

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex